import os
from src.llm_manager import llm_manager

# Import all tools from tool modules
from src.tools.memory_tools import search_second_brain, write_lesson, pinterest_search, pinterest_pin
from src.tools.dev_tools import write_file, run_code, github_push, ssh_execute
from src.tools.comms_tools import send_email, read_email, calendar_event, draft_document
from src.tools.media_tools import text_to_speech, edit_video
from src.tools.social_tools import post_to_x, post_to_instagram, post_to_linkedin, post_to_youtube, schedule_post
from src.tools.research_tools import web_search, read_webpage, browse_web, download_file, summarize_content

# Global Central Tool Registry mapping tool names to executable LangChain @tool objects
TOOL_REGISTRY = {
    # Memory & Intelligence
    "search_second_brain": search_second_brain,
    "write_lesson": write_lesson,
    "pinterest_search": pinterest_search,
    "pinterest_pin": pinterest_pin,
    
    # Code & Development
    "write_file": write_file,
    "run_code": run_code,
    "github_push": github_push,
    "ssh_execute": ssh_execute,
    
    # Communication & Productivity
    "send_email": send_email,
    "read_email": read_email,
    "calendar_event": calendar_event,
    "draft_document": draft_document,
    
    # Media & Content Creation
    "text_to_speech": text_to_speech,
    "edit_video": edit_video,
    
    # Social Media Management
    "post_to_x": post_to_x,
    "post_to_instagram": post_to_instagram,
    "post_to_linkedin": post_to_linkedin,
    "post_to_youtube": post_to_youtube,
    "schedule_post": schedule_post,
    
    # Browser & Research
    "web_search": web_search,
    "read_webpage": read_webpage,
    "browse_web": browse_web,
    "download_file": download_file,
    "summarize_content": summarize_content
}

def get_clean_content_str(content) -> str:
    """Helper to convert string or list-based content into a clean string."""
    if isinstance(content, list):
        text_parts = []
        for part in content:
            if isinstance(part, dict) and "text" in part:
                text_parts.append(part["text"])
            else:
                text_parts.append(str(part))
        return "".join(text_parts)
    return str(content)

def run_agent(role_description: str, task: str, tool_names: list, messages: list = None, intensity: str = "heavy") -> str:
    """
    Universal agent runner function.
    Dynamically creates and executes any sub-agent on the fly with custom role descriptions and assigned toolsets.
    Executes tool calls when generated by LLM and passes back results.
    """
    assigned_tools = [TOOL_REGISTRY[name] for name in tool_names if name in TOOL_REGISTRY]
    
    system_message = (
        f"You are a specialized sub-agent for Agent Milo. Role: {role_description}.\n"
        f"Your task: {task}\n"
        "Use your assigned tools efficiently to accomplish the goal cleanly."
    )
    
    input_messages = [{"role": "system", "content": system_message}]
    if messages:
        input_messages.extend(messages)
    else:
        input_messages.append({"role": "user", "content": task})
        
    print(f"[Dynamic Sub-Agent: {role_description}] Running with tools: {[t.name for t in assigned_tools]} (Intensity: '{intensity}')")
    
    response = llm_manager.invoke_with_waterfall(
        prompt_or_messages=input_messages,
        intensity=intensity,
        tools=assigned_tools if assigned_tools else None
    )
    
    # Handle Tool Calls generated by LLM
    if hasattr(response, "tool_calls") and response.tool_calls:
        results = []
        for tc in response.tool_calls:
            t_name = tc.get("name")
            t_args = tc.get("args", {})
            print(f"  [Tool Executing] Running '{t_name}' with args: {t_args}")
            if t_name in TOOL_REGISTRY:
                try:
                    tool_output = TOOL_REGISTRY[t_name].invoke(t_args)
                    results.append(f"Output of {t_name}:\n{tool_output}")
                except Exception as e:
                    results.append(f"Error executing {t_name}: {str(e)}")
        
        # Second pass to synthesize final output with tool results
        synthesis_messages = input_messages + [
            response,
            {"role": "user", "content": f"Tool Execution Results:\n" + "\n\n".join(results) + "\n\nPlease summarize final completion status for user."}
        ]
        synth_response = llm_manager.invoke_with_waterfall(
            prompt_or_messages=synthesis_messages,
            intensity="light"
        )
        return get_clean_content_str(synth_response.content)
        
    return get_clean_content_str(response.content)

def run_worker_agent(role: str, messages: list) -> str:
    all_tool_names = list(TOOL_REGISTRY.keys())
    return run_agent(role_description=f"Specialized {role}", task="Execute task based on message history", tool_names=all_tool_names, messages=messages)
